openapi: 3.1.0
info:
  title: Cargo Tracking API
  version: 1.0.0

tags:
  - name: Route
    description: Route API

paths:
  /api/v1/routes:
    post:
      summary: Создать новый маршрут
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRouteRequest'
      responses:
        '201':
          description: Маршрут успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRouteResponse'
        '400':
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Недостаточно прав для выполнения операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Route

    get:
      summary: Получить список маршрутов
      description: Возвращает список маршрутов с поддержкой пагинации.
      parameters:
        - name: page
          in: query
          description: Номер страницы, начиная с 0.
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          description: Количество элементов на странице.
          required: false
          schema:
            type: integer
            minimum: 1
            default: 20
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/PaginationResponse'

  /api/v1/routes/{routeId}:
    get:
      summary: Получить информацию о маршруте
      parameters:
        - name: routeId
          in: path
          required: true
          schema:
            type: long
          description: Идентификатор маршрута
      responses:
        '200':
          description: Информация о маршруте
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRouteResponse'
        '404':
          description: Маршрут не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Route

    put:
      summary: Обновить маршрут
      parameters:
        - name: routeId
          in: path
          required: true
          schema:
            type: long
          description: Идентификатор маршрута
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRouteRequest'
      responses:
        '200':
          description: Маршрут успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRouteResponse'
        '400':
          description: Ошибка валидации данных
        '403':
          description: Недостаточно прав для выполнения операции
        '404':
          description: Маршрут не найден
      tags:
        - Route

    delete:
      summary: Удалить маршрут
      parameters:
        - name: routeId
          in: path
          required: true
          schema:
            type: long
          description: Идентификатор маршрута
      responses:
        '204':
          description: Маршрут успешно удален
        '403':
          description: Недостаточно прав для выполнения операции
        '404':
          description: Маршрут не найден
      tags:
        - Route

  /api/v1/routes/markPoints/{routeId}:
    put:
      summary: Пометить точку маршрута как посещенную
      parameters:
        - name: routeId
          in: path
          required: true
          schema:
            type: long
          description: Идентификатор маршрута
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  latitude:
                    type: number
                    format: float
                  longitude:
                    type: number
                    format: float
                  isVisited:
                    type: boolean
                  id:
                    type: long
              description: Массив координат маршрута
      responses:
        '200':
          description: Успешное выполнение
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GetRouteResponse'
        '400':
          description: Ошибка запроса
        '404':
          description: Маршрут не найден

  /api/v1/routes/user/{userId}:
    get:
      summary: Получить список маршрутов пользователя
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: Id пользователя
        - name: page
          in: query
          description: Номер страницы, начиная с 0.
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          description: Количество элементов на странице.
          required: false
          schema:
            type: integer
            minimum: 1
            default: 20
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/PaginationResponse'
        '404':
          description: Маршруты не найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Route


components:
  schemas:
    PaginationResponse:
      type: object
      properties:
        content:
          type: array
          items:
            type: long
            description: Список идентификаторов маршрутов.
        totalPages:
          type: integer
          description: Общее количество страниц.
        totalElements:
          type: integer
          description: Общее количество элементов.
        last:
          type: boolean
          description: Признак последней страницы.
        size:
          type: integer
          minimum: 1
          description: Количество элементов на странице.
        number:
          type: integer
          minimum: 0
          description: Номер текущей страницы.
        numberOfElements:
          type: integer
          description: Количество элементов на текущей странице.
        first:
          type: boolean
          description: Признак первой страницы.
        empty:
          type: boolean
          description: Признак пустой страницы.
    CreateRouteRequest:
      type: object
      properties:
        id:
          type: long
          description: Уникальный идентификатор маршрута
        name:
          type: string
          description: Название маршрута
        description:
          type: string
          description: Описание маршрута
        assignedUsername:
          type: string
          description: Имя пользователя
        coordinates:
          type: array
          items:
            type: object
            properties:
              latitude:
                type: number
                format: float
              longitude:
                type: number
                format: float
          description: Массив координат маршрута
      required:
        - coordinates
    GetRouteResponse:
      type: object
      properties:
        id:
          type: long
          description: Уникальный идентификатор созданного маршрута
        name:
          type: string
          description: Название маршрута
        description:
          type: string
          description: Описание маршрута
        assignedUsername:
          type: string
          description: Имя пользователя на которого назначен маршрут
        coordinates:
          type: array
          items:
            type: object
            properties:
              latitude:
                type: number
                format: float
              longitude:
                type: number
                format: float
              isVisited:
                type: boolean
              id:
                type: long
          description: Массив координат маршрута
      required:
        - id
        - coordinates
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Описание ошибки
