openapi: 3.1.0
info:
  title: Cargo Tracking API
  version: 1.0.0

tags:
  - name: Cargo
    description: Cargo api
paths:
  /api/v1/vehicles:
    get:
      summary: Получить список транспортных средств
      responses:
        '200':
          description: Список транспортных средств
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
      tags:
        - Cargo
    post:
      summary: Добавить новое транспортное средство
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleCreateRequest'
      responses:
        '201':
          description: Транспортное средство успешно добавлено
      tags:
        - Cargo
  /api/v1/vehicles/{vehicleId}:
    get:
      summary: Получить информацию о транспортном средстве
      parameters:
        - name: vehicleId
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
          description: Идентификатор транспортного средства
      responses:
        '200':
          description: Информация о транспортном средстве
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '404':
          description: Транспортное средство не найдено
      tags:
        - Cargo
  /api/v1/cargo:
    get:
      summary: Получить список грузов
      responses:
        '200':
          description: Список грузов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cargo'
      tags:
        - Cargo
    post:
      summary: Добавить новый груз
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CargoCreateRequest'
      responses:
        '201':
          description: Груз успешно добавлен
      tags:
        - Cargo
  /api/v1/cargo/{cargoId}:
    get:
      summary: Получить информацию о грузе
      parameters:
        - name: cargoId
          in: path
          required: true
          schema:
            type: integer
          description: Идентификатор груза
      responses:
        '200':
          description: Информация о грузе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cargo'
        '404':
          description: Груз не найден
      tags:
        - Cargo
  /api/v1/cargo-location/{cargoId}:
    get:
      summary: Получить местоположение груза
      parameters:
        - name: cargoId
          in: path
          required: true
          schema:
            type: integer
          description: Идентификатор груза
      responses:
        '200':
          description: Местоположение груза
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CargoLocation'
        '404':
          description: Груз или местоположение не найдено
      tags:
        - Cargo

components:
  schemas:
    Vehicle:
      type: object
      properties:
        vehicle_id:
          type: integer
        driver_id:
          type: integer
        description:
          type: string
        name:
          type: string
    VehicleCreateRequest:
      type: object
      required:
        - driver_id
        - name
      properties:
        driver_id:
          type: integer
        description:
          type: string
        name:
          type: string
          maxLength: 25
    Cargo:
      type: object
      properties:
        cargo_id:
          type: integer
        name:
          type: string
          maxLength: 50
        description:
          type: string
        weight:
          type: number
        status:
          type: string
          maxLength: 50
        created_at:
          type: string
          format: date-time
        vehicle_id:
          type: integer
    CargoCreateRequest:
      type: object
      required:
        - name
        - weight
        - vehicle_id
      properties:
        name:
          type: string
          maxLength: 50
        description:
          type: string
        weight:
          type: number
        status:
          type: string
          maxLength: 50
    CargoLocation:
      type: object
      properties:
        location_id:
          type: integer
        cargo_id:
          type: integer
        location:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
