version: '3'

networks:
  overlay:

volumes:
  pg_data:
    driver: local

services:
  db:
    image: binakot/postgresql-postgis-timescaledb:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - overlay
    volumes:
      - pg_data:/var/lib/postgresql/data
