spring:
  application:
    name: cargo-eureka
eureka:
  server:
    response-cache-update-interval-ms: 1000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8761

logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'