spring:
  application:
    name: ${APP_NAME:CargoTransportationMonitoringApplication}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/realms/cargotransportation-realm/protocol/openid-connect/certs}

server:
  port: ${SERVER_PORT:8083}

eureka:
  instance:
    instance-id: ${EUREKA_INSTANCE_ID:${spring.application.name}:${random.value}}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8081}
  resource: ${KEYCLOAK_RESOURCE:user-manage-client}
  realm: ${KEYCLOAK_REALM:cargotransportation-realm}
  use-resource-role-mappings: ${KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS:true}
  ssl-required: ${KEYCLOAK_SSL_REQUIRED:external}
  credentials:
    secret: ${KEYCLOAK_SECRET:i4OU48rv7gIsXkp5303iIvSCrYGbeM5F}

client:
  url: ${CLIENT_URL:http://localhost:3000}

secret:
  key: ${SECRET:1234567890101112}

route:
  service:
    url: ${ROUTE_SERVICE_URL:http://localhost:8082}