spring:
  application:
    name: ${APP_NAME:CargoTrackingService}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/realms/cargotransportation-realm/protocol/openid-connect/certs}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8084}
