spring:
  application:
    name: CargoRoute
  datasource:
    url: jdbc:postgresql://localhost:5432/route
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/cargotransportation-realm/protocol/openid-connect/certs
server:
  port: 8082

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

client:
  url: http://localhost:3000

core:
  url: http://localhost:8081


keycloak:
  auth-server-url: http://localhost:8080
  resource: user-manage-client
  realm: cargotransportation-realm
  use-resource-role-mappings: true
  ssl-required: external
  credentials:
    secret: oUz5y5x5A9Z6PChPadWEm55X2socNNQR